In [25]:
import keras
import tensorflow as tf
from keras.datasets import mnist
from keras.models import Sequential
from keras.layers import Dense, Dropout
from keras.layers import Flatten, Conv2D, MaxPooling2D

In [26]:
(X_train, y_train), (X_valid, y_valid) = mnist.load_data()

In [27]:
X_train.shape, X_valid.shape

((60000, 28, 28), (10000, 28, 28))

In [28]:
# y = labels
y_train.shape, y_valid.shape

((60000,), (10000,))

In [29]:
X_train = X_train.reshape(60000, 28, 28, 1)
X_valid = X_valid.reshape(10000, 28, 28, 1)

X_train.shape, X_valid.shape

((60000, 28, 28, 1), (10000, 28, 28, 1))

In [30]:
# for better imagination of shape, try to find last values in every index
X_train[59999][27][27][0]
# This seems very simple but in this approach you can find seed to imagine this shape, 
# and get intuition how to get access to every places in this space.

0

In [31]:
# do you see differences? 
X_train.dtype, X_train.astype('float32').dtype

(dtype('uint8'), dtype('float32'))

In [32]:
X_train = X_train.astype('float32')
X_valid = X_valid.astype('float32')

X_train.dtype, X_valid.dtype

(dtype('float32'), dtype('float32'))

In [33]:
X_train[0, 0:27, 0:27, 0]

array([[  0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
          0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
          0.,   0.,   0.,   0.,   0.],
       [  0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
          0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
          0.,   0.,   0.,   0.,   0.],
       [  0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
          0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
          0.,   0.,   0.,   0.,   0.],
       [  0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
          0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
          0.,   0.,   0.,   0.,   0.],
       [  0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
          0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
          0.,   0.,   0.,   0.,   0.],
       [  0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0

In [34]:
t = tf.constant([[10, 10, 2, 2]])
t[0][0:4]
# w tym momencie coś mi się pojebało... tak dosłownie . .

<tf.Tensor: shape=(4,), dtype=int32, numpy=array([10, 10,  2,  2], dtype=int32)>

In [35]:
# this replace current numbers (from range 0 255) to values from range between 0 and 1
X_train /= 255
X_valid /= 255

In [36]:
len(y_train), len(y_valid)

(60000, 10000)

In [37]:
y_train[0:2], y_valid[0:2]

(array([5, 0], dtype=uint8), array([7, 2], dtype=uint8))

In [38]:
# look differences between above and under y_train
num_classes = 10
y_train = tf.keras.utils.to_categorical(y_train, num_classes=num_classes)
y_valid = tf.keras.utils.to_categorical(y_valid, num_classes=num_classes)

y_train[0:2], y_valid[0:2]

(array([[0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
        [1., 0., 0., 0., 0., 0., 0., 0., 0., 0.]], dtype=float32),
 array([[0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
        [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.]], dtype=float32))

# CREATE MODEL ARCHITECTURE

In [39]:
# create empty model
model = Sequential()

In [40]:
type(model)

keras.engine.sequential.Sequential

In [41]:
# First convolution layer
model.add(Conv2D(32, 
                 kernel_size=(3, 3), 
                 activation='relu', 
                 input_shape=(28, 28, 1)
                 ))

In [42]:
# Second convolution layer
model.add(Conv2D(64, kernel_size=(3, 3), activation='relu'))
model.add(MaxPooling2D(2, 2))
tf.random.set_seed(0)
model.add(Dropout(0.25))
model.add(Flatten())

In [43]:
# Third hidden layer
model.add(Dense(128, activation='relu'))
model.add(Dropout(0.5))


In [44]:
# Output layer
model.add(Dense(num_classes, activation='softmax'))

In [45]:
model.summary()

Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 conv2d_2 (Conv2D)           (None, 26, 26, 32)        320       
                                                                 
 conv2d_3 (Conv2D)           (None, 24, 24, 64)        18496     
                                                                 
 max_pooling2d_1 (MaxPooling  (None, 12, 12, 64)       0         
 2D)                                                             
                                                                 
 dropout_2 (Dropout)         (None, 12, 12, 64)        0         
                                                                 
 flatten_1 (Flatten)         (None, 9216)              0         
                                                                 
 dense_2 (Dense)             (None, 128)               1179776   
                                                      

In [46]:
# model configuration
model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])

In [47]:
model.fit(X_train, y_train, batch_size=128, epochs=10, verbose=1, validation_data=(X_valid, y_valid))

Epoch 1/10
469/469 [==============================] - 75s 158ms/step - loss: 0.2470 - accuracy: 0.9238 - val_loss: 0.0536 - val_accuracy: 0.9831
Epoch 2/10
469/469 [==============================] - 70s 150ms/step - loss: 0.0874 - accuracy: 0.9740 - val_loss: 0.0432 - val_accuracy: 0.9848
Epoch 3/10
469/469 [==============================] - 67s 144ms/step - loss: 0.0670 - accuracy: 0.9798 - val_loss: 0.0296 - val_accuracy: 0.9899
Epoch 4/10
469/469 [==============================] - 70s 150ms/step - loss: 0.0514 - accuracy: 0.9845 - val_loss: 0.0340 - val_accuracy: 0.9884
Epoch 5/10
469/469 [==============================] - 68s 144ms/step - loss: 0.0457 - accuracy: 0.9855 - val_loss: 0.0261 - val_accuracy: 0.9918
Epoch 6/10
469/469 [==============================] - 69s 148ms/step - loss: 0.0415 - accuracy: 0.9867 - val_loss: 0.0299 - val_accuracy: 0.9905
Epoch 7/10
469/469 [==============================] - 67s 144ms/step - loss: 0.0360 - accuracy: 0.9887 - val_loss: 0.0259 - val_ac

# 11001  00110